import http from 'node:http';
import {createHmac,randomUUID,timingSafeEqual} from 'node:crypto';
import {createReadStream,createWriteStream} from 'node:fs';
import {copyFile,link,mkdir,readFile,rename,rm,stat,unlink,writeFile} from 'node:fs/promises';
import {pipeline} from 'node:stream/promises';
import {fileURLToPath} from 'node:url';
import net from 'node:net';
import {dirname} from 'node:path';
import {chromium} from 'playwright-core';
import WebSocket,{WebSocketServer} from 'ws';

const PORT=Number(process.env.PORT||3000),TOKEN=String(process.env.ACCESS_TOKEN||'');
const DATA_DIR=String(process.env.DATA_DIR||'/data'),PROFILE_DIR=String(process.env.PROFILE_DIR||DATA_DIR+'/chromium-profile');
const HOME_URL=String(process.env.HOME_URL||'https://example.com'),QUALITY=Math.max(35,Math.min(90,Number(process.env.SCREEN_QUALITY||72)));
const MAX_TABS=Math.max(1,Math.min(20,Number(process.env.MAX_TABS||8))),LOAD_DEADLINE=Math.max(3000,Math.min(120000,Number(process.env.SITE_LOAD_TIMEOUT_MS||25000)));
const HEADLESS=String(process.env.BROWSER_HEADLESS??'true').toLowerCase()!=='false',IGNORE_TLS=String(process.env.IGNORE_HTTPS_ERRORS??'true').toLowerCase()!=='false';
const LOCALE=String(process.env.BROWSER_LOCALE||'fa-IR'),TIMEZONE=String(process.env.BROWSER_TIMEZONE||'Asia/Tehran');
const SECURE_COOKIE=String(process.env.SECURE_COOKIE??'true').toLowerCase()!=='false',ALLOW_PRIVATE_TEST=String(process.env.ALLOW_PRIVATE_TEST||'').toLowerCase()==='true';
const UPLOAD_LIMIT=Math.max(1,Math.min(128,Number(process.env.UPLOAD_LIMIT_MB||32)))*1024*1024;
const AUTH_COOKIE=SECURE_COOKIE?'__Host-railway_browser':'railway_browser',DOWNLOAD_DIR=DATA_DIR+'/downloads',UPLOAD_DIR=DATA_DIR+'/uploads',DOWNLOAD_INDEX=DATA_DIR+'/download-index.json';
const PUBLIC_DIR=fileURLToPath(new URL('./public/',import.meta.url));
const ASSETS=new Map([['/',{file:'index.html',type:'text/html; charset=utf-8'}],['/app',{file:'index.html',type:'text/html; charset=utf-8'}],['/app.css',{file:'app.css',type:'text/css; charset=utf-8'}],['/app.js',{file:'app.js',type:'text/javascript; charset=utf-8'}]]);

const json=(res,status,value,headers={})=>{const body=JSON.stringify(value);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','content-length':Buffer.byteLength(body),...headers});res.end(body)};
const readBody=async(req,limit=50*1024*1024)=>{const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>limit)throw Error('Request body too large');chunks.push(c)}return Buffer.concat(chunks)};
const parseCookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split(/=(.*)/s)).filter(x=>x[0]).map(([k,v=''])=>[k,decodeURIComponent(v)]));
const session=()=>createHmac('sha256',TOKEN).update('railway-browser:v5').digest('base64url');
const safeEqual=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y)};
const authed=req=>Boolean(TOKEN&&safeEqual(parseCookies(req)[AUTH_COOKIE]||'',session()));
const authCookie=(value,age)=>AUTH_COOKIE+'='+encodeURIComponent(value)+'; Path=/; HttpOnly; '+(SECURE_COOKIE?'Secure; ':'')+'SameSite=Strict; Max-Age='+age;
const base=req=>'http:'+'//'+(req.headers.host||'localhost');
const publicHeaders={'cache-control':'no-store','content-security-policy':"default-src 'self'; img-src 'self' data:; connect-src 'self' ws: wss:; style-src 'self'; script-src 'self'; frame-ancestors 'none'; base-uri 'none'",'referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY'};

function safeName(name){return String(name||'file').normalize('NFKC').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').replace(/^\.+/,'').slice(0,180)||'file'}
function mime(name){const e=name.toLowerCase().split('.').pop();return({pdf:'application/pdf',zip:'application/zip',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',mp4:'video/mp4',mp3:'audio/mpeg',txt:'text/plain; charset=utf-8',json:'application/json',csv:'text/csv; charset=utf-8'})[e]||'application/octet-stream'}
function endpoint(value){let v=String(value||'').trim();if(!v)return'';if(!/^https?:\/\//i.test(v))v='https://'+v;return v.replace(/\/+$/,'')}
function blockedHost(host){if(ALLOW_PRIVATE_TEST)return false;host=String(host||'').toLowerCase().replace(/^\[|\]$/g,'');if(['localhost','metadata.google.internal','instance-data.ec2.internal'].includes(host)||host.endsWith('.local')||host.endsWith('.internal'))return true;const t=net.isIP(host);if(t===6)return host==='::'||host==='::1'||host.startsWith('fc')||host.startsWith('fd')||/^fe[89ab]/.test(host);if(t===4){const[a,b]=host.split('.').map(Number);return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224}return false}
function normalizeUrl(value){let v=String(value||'').trim();if(!v)return HOME_URL;if(!/^[a-z][a-z\d+.-]*:/i.test(v))v='https:'+'//'+v;const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||blockedHost(u.hostname))throw Error('این آدرس مجاز نیست');return u.href}

class DownloadStore{
  constructor(onChange){this.onChange=onChange;this.records=[];this.client=null;this.s3=null;this.signer=null;this.requested=false;this.configured=false;this.error=null;this.prefix=String(process.env.S3_PREFIX||'browser-downloads').replace(/^\/+|\/+$/g,'');if(this.prefix)this.prefix+='/' }
  async init(){await Promise.all([mkdir(DOWNLOAD_DIR,{recursive:true}),mkdir(UPLOAD_DIR,{recursive:true})]);try{const x=JSON.parse(await readFile(DOWNLOAD_INDEX,'utf8'));if(Array.isArray(x))this.records=x.slice(0,500)}catch{}const required=['S3_BUCKET','S3_ACCESS_KEY_ID','S3_SECRET_ACCESS_KEY'];this.requested=required.some(k=>String(process.env[k]||''))||Boolean(process.env.S3_ENDPOINT);if(!this.requested)return;const missing=required.filter(k=>!String(process.env[k]||''));if(missing.length){this.error='S3 variables missing: '+missing.join(', ');return}try{const mod=await import('@aws-sdk/client-s3'),pre=await import('@aws-sdk/s3-request-presigner');this.s3=mod;this.signer=pre.getSignedUrl;const cfg={region:String(process.env.S3_REGION||'us-west-2'),credentials:{accessKeyId:String(process.env.S3_ACCESS_KEY_ID),secretAccessKey:String(process.env.S3_SECRET_ACCESS_KEY)},forcePathStyle:String(process.env.S3_FORCE_PATH_STYLE??'true').toLowerCase()!=='false',requestChecksumCalculation:'WHEN_REQUIRED',responseChecksumValidation:'WHEN_REQUIRED'};const ep=endpoint(process.env.S3_ENDPOINT);if(ep)cfg.endpoint=ep;this.client=new mod.S3Client(cfg);this.configured=true;this.error=null}catch(e){this.error='S3 disabled: '+e.message;console.error(this.error)}}
  summary(){let ep=endpoint(process.env.S3_ENDPOINT);try{if(ep)ep=new URL(ep).host}catch{}return{requested:this.requested,configured:this.configured,mode:this.configured?'s3':'local',bucket:this.requested?String(process.env.S3_BUCKET||''):null,endpoint:ep||null,error:this.error}}
  clean(r){return{id:r.id,name:r.name,size:r.size||0,status:r.status,location:r.location||null,key:r.key||null,createdAt:r.createdAt,warning:r.warning||null,error:r.error||null}}
  list(){return this.records.map(r=>this.clean(r))}
  find(id){return this.records.find(r=>r.id===id)}
  async save(){const tmp=DOWNLOAD_INDEX+'.tmp';await writeFile(tmp,JSON.stringify(this.records));await rename(tmp,DOWNLOAD_INDEX)}
  notify(r){this.onChange?.({type:'download:update',download:this.clean(r),storage:this.summary()})}
  async capture(download){const id=randomUUID(),name=safeName(download.suggestedFilename()),now=new Date().toISOString(),r={id,name,size:0,status:'downloading',location:null,key:null,localPath:null,warning:null,error:null,createdAt:now};this.records.unshift(r);this.records=this.records.slice(0,500);await this.save();this.notify(r);const local=DOWNLOAD_DIR+'/'+id+'-'+name;try{await download.saveAs(local);const failure=await download.failure();if(failure)throw Error(failure);const info=await stat(local);r.size=info.size;r.location='local';r.localPath=local;if(this.configured){try{const key=this.prefix+now.slice(0,10).replaceAll('-','/')+'/'+id+'-'+name;await this.client.send(new this.s3.PutObjectCommand({Bucket:String(process.env.S3_BUCKET),Key:key,Body:createReadStream(local),ContentLength:info.size,ContentType:mime(name),ContentDisposition:"attachment; filename*=UTF-8''"+encodeURIComponent(name)}));await unlink(local).catch(()=>{});r.location='s3';r.localPath=null;r.key=key}catch(e){r.warning='S3 upload failed; kept locally: '+e.message;this.error=r.warning}}r.status='stored'}catch(e){r.status='failed';r.error=e.message;await unlink(local).catch(()=>{})}await this.save();this.notify(r)}
  async materialize(id){const r=this.find(id);if(!r||r.status!=='stored')throw Error('فایل دانلودشده پیدا نشد');const dir=UPLOAD_DIR+'/'+randomUUID();await mkdir(dir,{recursive:true});const path=dir+'/'+safeName(r.name);if(r.location==='local'){await stat(r.localPath);try{await link(r.localPath,path)}catch{await copyFile(r.localPath,path)}return{path,temporary:true,name:r.name}}if(!this.configured)throw Error('S3 در دسترس نیست');const out=await this.client.send(new this.s3.GetObjectCommand({Bucket:String(process.env.S3_BUCKET),Key:r.key}));if(out.Body?.transformToByteArray){await writeFile(path,Buffer.from(await out.Body.transformToByteArray()))}else if(out.Body){await pipeline(out.Body,createWriteStream(path))}else throw Error('بدنه فایل از S3 دریافت نشد');return{path,temporary:true,name:r.name}}
  async accessUrl(id){const r=this.find(id);if(!r||r.status!=='stored')throw Error('Download not found');if(r.location==='local')return{url:'/api/downloads/'+encodeURIComponent(id)+'/file'};if(!this.configured)throw Error('S3 unavailable');const ttl=Math.max(60,Math.min(86400,Number(process.env.S3_SIGNED_URL_TTL||900))),cmd=new this.s3.GetObjectCommand({Bucket:String(process.env.S3_BUCKET),Key:r.key,ResponseContentDisposition:"attachment; filename*=UTF-8''"+encodeURIComponent(r.name)});return{url:await this.signer(this.client,cmd,{expiresIn:ttl}),expiresIn:ttl}}
  async remove(id){const i=this.records.findIndex(r=>r.id===id);if(i<0)throw Error('Not found');const r=this.records[i];if(r.location==='s3'&&r.key&&this.configured)await this.client.send(new this.s3.DeleteObjectCommand({Bucket:String(process.env.S3_BUCKET),Key:r.key}));if(r.localPath)await unlink(r.localPath).catch(()=>{});this.records.splice(i,1);await this.save();this.onChange?.({type:'download:removed',id,storage:this.summary()})}
}

class BrowserHub{
  constructor(store){this.store=store;this.context=null;this.records=new Map();this.pageIds=new WeakMap();this.activeId=null;this.clients=new Set();this.ready=false;this.captureToken=0;this.pendingChoosers=new Map()}
  broadcast(v){const data=JSON.stringify(v);for(const ws of this.clients)if(ws.readyState===WebSocket.OPEN)ws.send(data)}
  state(){return{type:'state',ready:this.ready,activeId:this.activeId,tabs:[...this.records.values()].map(r=>({id:r.id,title:r.title||'تب جدید',url:r.url||'about:blank',active:r.id===this.activeId,loading:Boolean(r.loading),crashed:Boolean(r.crashed)})),storage:this.store.summary(),limits:{uploadBytes:UPLOAD_LIMIT,loadTimeoutMs:LOAD_DEADLINE}}}
  broadcastState(){this.broadcast(this.state())}
  active(){return this.records.get(this.activeId)}
  addClient(ws){this.clients.add(ws);ws.send(JSON.stringify(this.state()));ws.send(JSON.stringify({type:'downloads',items:this.store.list(),storage:this.store.summary()}));this.snapshot(this.active(),ws).catch(()=>{});ws.on('close',()=>this.clients.delete(ws))}
  async start(){await mkdir(PROFILE_DIR,{recursive:true});const options={headless:HEADLESS,viewport:{width:1440,height:900},locale:LOCALE,timezoneId:TIMEZONE,ignoreHTTPSErrors:IGNORE_TLS,acceptDownloads:true,args:['--disable-dev-shm-usage','--no-sandbox','--disable-setuid-sandbox','--disable-quic','--disable-popup-blocking','--autoplay-policy=no-user-gesture-required','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows','--host-resolver-rules=MAP metadata.google.internal ~NOTFOUND, MAP instance-data.ec2.internal ~NOTFOUND']};if(process.env.CHROMIUM_PATH)options.executablePath=String(process.env.CHROMIUM_PATH);this.context=await chromium.launchPersistentContext(PROFILE_DIR,options);this.context.setDefaultTimeout(30000);this.context.on('page',p=>this.ensure(p,true).catch(()=>{}));await this.context.route('**/*',async route=>{try{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&blockedHost(u.hostname))return route.abort('blockedbyclient')}catch{}return route.continue()});for(const p of this.context.pages())await this.ensure(p,false);if(!this.records.size)await this.newTab(HOME_URL);else{const first=[...this.records.values()].find(r=>r.url!=='about:blank')||[...this.records.values()][0];if(first.url==='about:blank')await this.navigate(first,HOME_URL);await this.activate(first.id)}this.ready=true;this.broadcastState();await this.snapshot(this.active()).catch(()=>{})}
  async ensure(page,activate=false){if(this.pageIds.has(page)){const id=this.pageIds.get(page);if(activate)await this.activate(id);return id}const id=randomUUID(),r={id,page,title:'تب جدید',url:page.url()||'about:blank',session:null,loading:false,navSeq:0,crashed:false};this.pageIds.set(page,id);this.records.set(id,r);const refresh=async()=>{await this.update(r);if(this.activeId===id)await this.snapshot(r).catch(()=>{})};page.on('framenavigated',f=>{if(f===page.mainFrame())this.update(r).catch(()=>{})});page.on('domcontentloaded',refresh);page.on('load',refresh);page.on('download',d=>this.store.capture(d).catch(()=>{}));page.on('filechooser',c=>this.fileChooser(r,c));page.on('crash',()=>this.crash(r));page.on('close',()=>this.closed(id));await this.update(r,false);if(activate)await this.activate(id);else this.broadcastState();return id}
  async update(r,broadcast=true){if(!r||r.page.isClosed())return;r.url=r.page.url()||'about:blank';let fallback='تب جدید';try{fallback=new URL(r.url).hostname||fallback}catch{}r.title=(await r.page.title().catch(()=>''))||fallback;if(broadcast)this.broadcastState()}
  async snapshot(r=this.active(),onlyWs=null){if(!r||r.page.isClosed())return;const buf=await r.page.screenshot({type:'jpeg',quality:QUALITY,animations:'disabled'}),msg=JSON.stringify({type:'frame',tabId:r.id,data:buf.toString('base64'),metadata:{snapshot:true}});if(onlyWs){if(onlyWs.readyState===WebSocket.OPEN)onlyWs.send(msg)}else for(const ws of this.clients)if(ws.readyState===WebSocket.OPEN)ws.send(msg)}
  async stopLoading(r=this.active(),reason='manual'){if(!r||r.page.isClosed())return;r.navSeq++;r.loading=false;try{if(r.session)await r.session.send('Page.stopLoading')}catch{}try{await r.page.evaluate(()=>window.stop())}catch{}this.broadcast({type:'navigation',phase:'stopped',tabId:r.id,reason});this.broadcastState();await this.snapshot(r).catch(()=>{})}
  async navigate(r,value){const url=normalizeUrl(value),seq=++r.navSeq;r.loading=true;r.crashed=false;this.broadcastState();this.broadcast({type:'navigation',phase:'start',tabId:r.id,url});const nav=r.page.goto(url,{waitUntil:'domcontentloaded',timeout:LOAD_DEADLINE+5000}).then(()=>({ok:true}),e=>({ok:false,error:e}));let timer;const deadline=new Promise(resolve=>{timer=setTimeout(()=>resolve({deadline:true}),LOAD_DEADLINE);timer.unref?.()});const result=await Promise.race([nav,deadline]);clearTimeout(timer);if(seq!==r.navSeq)return;if(result.deadline){await this.stopLoading(r,'timeout')}else if(!result.ok){await this.stopLoading(r,'error');this.broadcast({type:'browser:error',tabId:r.id,message:result.error.message})}else{r.loading=false;await this.update(r);await this.snapshot(r).catch(()=>{});this.broadcast({type:'navigation',phase:'done',tabId:r.id,url:r.page.url()})}this.broadcastState()}
  async crash(r){if(!this.records.has(r.id)||r.crashed)return;r.crashed=true;r.loading=false;this.broadcast({type:'tab:crashed',tabId:r.id,message:'تب کرش کرد و بسته شد؛ تب‌های دیگر قابل استفاده‌اند.'});await r.page.close().catch(()=>{});if(!this.records.size)await this.newTab(HOME_URL)}
  async stopCapture(r){if(!r?.session)return;try{await r.session.send('Page.stopScreencast')}catch{}try{await r.session.detach()}catch{}r.session=null}
  async startCapture(r){const token=++this.captureToken;await this.stopCapture(r);const s=await this.context.newCDPSession(r.page);r.session=s;s.on('Page.screencastFrame',async e=>{try{await s.send('Page.screencastFrameAck',{sessionId:e.sessionId})}catch{}if(token===this.captureToken&&this.activeId===r.id)this.broadcast({type:'frame',tabId:r.id,data:e.data,metadata:e.metadata})});await s.send('Page.startScreencast',{format:'jpeg',quality:QUALITY,maxWidth:1440,maxHeight:900,everyNthFrame:1});await this.snapshot(r).catch(()=>{})}
  async activate(id){const r=this.records.get(id);if(!r||r.page.isClosed())return;const old=this.records.get(this.activeId);if(old&&old!==r)await this.stopCapture(old);this.activeId=id;await r.page.bringToFront().catch(()=>{});await this.startCapture(r);await this.update(r,false);this.broadcastState()}
  async newTab(url=HOME_URL){if(this.records.size>=MAX_TABS)throw Error('حداکثر تعداد تب‌ها '+MAX_TABS+' است');const p=await this.context.newPage(),id=await this.ensure(p,false);await this.activate(id);this.navigate(this.records.get(id),url).catch(()=>{});return id}
  async closeTab(id){const r=this.records.get(id);if(!r)return;await r.page.close().catch(()=>{});if(!this.records.size)await this.newTab(HOME_URL)}
  async closed(id){const active=this.activeId===id;this.records.delete(id);if(!active)return this.broadcastState();this.activeId=null;const next=[...this.records.values()][0];if(next)await this.activate(next.id);else this.broadcastState()}
  fileChooser(r,chooser){const id=randomUUID(),timer=setTimeout(()=>this.pendingChoosers.delete(id),120000);timer.unref?.();this.pendingChoosers.set(id,{chooser,timer});this.broadcast({type:'filechooser',id,tabId:r.id,multiple:chooser.isMultiple(),downloads:this.store.list()})}
  async finishChooser(id,paths,temp=[]){const p=this.pendingChoosers.get(id);if(!p)throw Error('درخواست انتخاب فایل منقضی شده است');if(!p.chooser.isMultiple()&&paths.length>1)paths=paths.slice(0,1);await p.chooser.setFiles(paths);clearTimeout(p.timer);this.pendingChoosers.delete(id);setTimeout(()=>temp.forEach(async x=>{await unlink(x).catch(()=>{});await rm(dirname(x),{recursive:true,force:true}).catch(()=>{})}),60000).unref();this.broadcast({type:'filechooser:done',id,count:paths.length});return{ok:true,count:paths.length}}
  async uploadLocal(id,files){let total=0;const paths=[];for(const f of files){const buf=Buffer.from(String(f.data||''),'base64');total+=buf.length;if(total>UPLOAD_LIMIT)throw Error('حجم فایل‌ها بیشتر از حد مجاز است');const dir=UPLOAD_DIR+'/'+randomUUID();await mkdir(dir,{recursive:true});const path=dir+'/'+safeName(f.name);await writeFile(path,buf);paths.push(path)}return this.finishChooser(id,paths,paths)}
  async uploadDownloaded(id,downloadIds){const paths=[],temp=[];for(const itemId of downloadIds){const m=await this.store.materialize(itemId);paths.push(m.path);if(m.temporary)temp.push(m.path)}return this.finishChooser(id,paths,temp)}
  async message(raw){const m=typeof raw==='string'?JSON.parse(raw):raw;if(m.type==='tab.new')return this.newTab(m.url||HOME_URL);if(m.type==='tab.activate')return this.activate(m.id);if(m.type==='tab.close')return this.closeTab(m.id);const r=this.active();if(!r)return;if(m.type==='snapshot')return this.snapshot(r);if(m.type==='stop')return this.stopLoading(r,'manual');if(m.type==='navigate')return this.navigate(r,m.url);if(m.type==='back'){await r.page.goBack({waitUntil:'domcontentloaded',timeout:LOAD_DEADLINE}).catch(()=>{});await this.update(r);return this.snapshot(r)}if(m.type==='forward'){await r.page.goForward({waitUntil:'domcontentloaded',timeout:LOAD_DEADLINE}).catch(()=>{});await this.update(r);return this.snapshot(r)}if(m.type==='reload')return this.navigate(r,r.page.url());if(m.type==='home')return this.navigate(r,HOME_URL);if(m.type==='mouse'){if(m.action==='move')return r.page.mouse.move(Number(m.x),Number(m.y));if(m.action==='click')return r.page.mouse.click(Number(m.x),Number(m.y),{button:m.button||'left',clickCount:Number(m.clickCount||1)});if(m.action==='wheel')return r.page.mouse.wheel(Number(m.dx||0),Number(m.dy||0))}if(m.type==='text')return r.page.keyboard.insertText(String(m.text||''));if(m.type==='key'){const key=String(m.key||'');return(m.action==='up'?r.page.keyboard.up(key):r.page.keyboard.down(key)).catch(()=>{})}}
  async close(){for(const x of this.pendingChoosers.values())clearTimeout(x.timer);this.captureToken++;for(const r of this.records.values())await this.stopCapture(r);await this.context?.close()}
}

let hub;const store=new DownloadStore(e=>hub?.broadcast(e));hub=new BrowserHub(store);await store.init();
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,base(req));if(u.pathname==='/healthz')return json(res,hub.ready?200:503,{ok:hub.ready,browserReady:hub.ready,storage:store.summary()});if(u.pathname==='/api/status')return json(res,200,{configured:Boolean(TOKEN),authenticated:authed(req),browserReady:hub.ready,storage:authed(req)?store.summary():undefined});if(u.pathname==='/api/login'&&req.method==='POST'){if(!TOKEN)return json(res,503,{error:'ACCESS_TOKEN تنظیم نشده است'});const b=JSON.parse((await readBody(req,16384)).toString()||'{}');if(!safeEqual(b.token||'',TOKEN))return json(res,401,{error:'توکن نادرست است'});return json(res,200,{ok:true},{'set-cookie':authCookie(session(),43200)})}if(u.pathname==='/api/logout'&&req.method==='POST')return json(res,200,{ok:true},{'set-cookie':authCookie('',0)});if(u.pathname==='/api/upload/local'&&req.method==='POST'){if(!authed(req))return json(res,401,{error:'Unauthorized'});const b=JSON.parse((await readBody(req,UPLOAD_LIMIT*1.5+1024*1024)).toString()||'{}');return json(res,200,await hub.uploadLocal(b.chooserId,Array.isArray(b.files)?b.files:[]))}if(u.pathname==='/api/upload/download'&&req.method==='POST'){if(!authed(req))return json(res,401,{error:'Unauthorized'});const b=JSON.parse((await readBody(req,1024*1024)).toString()||'{}');return json(res,200,await hub.uploadDownloaded(b.chooserId,Array.isArray(b.downloadIds)?b.downloadIds:[]))}if(u.pathname==='/api/downloads'&&req.method==='GET'){if(!authed(req))return json(res,401,{error:'Unauthorized'});return json(res,200,{items:store.list(),storage:store.summary()})}let m=u.pathname.match(/^\/api\/downloads\/([^/]+)\/url$/);if(m&&req.method==='POST'){if(!authed(req))return json(res,401,{error:'Unauthorized'});return json(res,200,await store.accessUrl(decodeURIComponent(m[1])))}m=u.pathname.match(/^\/api\/downloads\/([^/]+)\/file$/);if(m&&req.method==='GET'){if(!authed(req))return json(res,401,{error:'Unauthorized'});const r=store.find(decodeURIComponent(m[1]));if(!r||r.location!=='local'||!r.localPath)return json(res,404,{error:'Not found'});const s=await stat(r.localPath);res.writeHead(200,{'content-type':mime(r.name),'content-length':s.size,'content-disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(r.name)});return createReadStream(r.localPath).pipe(res)}const asset=ASSETS.get(u.pathname);if(asset&&req.method==='GET'){const body=await readFile(PUBLIC_DIR+asset.file);res.writeHead(200,{...publicHeaders,'content-type':asset.type,'content-length':body.length});return res.end(body)}res.writeHead(404,publicHeaders);res.end('Not found')}catch(e){json(res,500,{error:e.message})}});
const wss=new WebSocketServer({noServer:true,maxPayload:1024*1024});server.on('upgrade',(req,socket,head)=>{try{const u=new URL(req.url,base(req));if(u.pathname!=='/ws'||!authed(req))throw Error('Unauthorized');wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws))}catch{socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');socket.destroy()}});wss.on('connection',ws=>{hub.addClient(ws);ws.on('message',d=>{hub.message(d.toString()).catch(e=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'browser:error',message:e.message}))})})});
server.listen(PORT,'0.0.0.0',()=>console.log('Railway browser v5 listening on '+PORT));hub.start().catch(e=>{console.error(e);setTimeout(()=>process.exit(1),1000).unref()});for(const sig of['SIGTERM','SIGINT'])process.on(sig,async()=>{await hub.close().catch(()=>{});server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),5000).unref()});
