import WebSocket from 'ws';
const proxy='http://127.0.0.1:3232';
const token='test-web-proxy-token-123456';
const login=await fetch(proxy+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});
if(!login.ok)throw Error('login failed '+login.status);
const cookie=login.headers.get('set-cookie').split(';')[0];
const get=(path,opt={})=>fetch(proxy+path,{redirect:'manual',...opt,headers:{cookie,...(opt.headers||{})}});
const root=await get('/p/http/127.0.0.1%3A3333/');const html=await root.text();
if(!html.includes('/p/http/127.0.0.1%3A3333/next'))throw Error('link was not rewritten');
if(!html.includes('/api/cookie'))throw Error('cookie bridge missing');
const next=await get('/p/http/127.0.0.1%3A3333/next');const nextText=await next.text();
if(!nextText.includes('session=alpha'))throw Error('target cookie not forwarded');
const post=await get('/p/http/127.0.0.1%3A3333/login',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:'u=test'});
console.log('post redirect',post.status,post.headers.get('location'));
if(post.status!==302||!String(post.headers.get('location')).includes('/p/http/127.0.0.1'))throw Error('redirect was not rewritten');
const account=await get('/p/http/127.0.0.1%3A3333/account');const accountText=await account.text();
if(!accountText.includes('session=alpha')||!accountText.includes('auth=ok'))throw Error('login cookies missing');
await new Promise((resolve,reject)=>{const ws=new WebSocket('ws://127.0.0.1:3232/ws?url='+encodeURIComponent('ws://127.0.0.1:3333/echo'),{headers:{Cookie:cookie}});const timer=setTimeout(()=>reject(Error('websocket timeout')),8000);ws.on('open',()=>ws.send('ping'));ws.on('message',d=>{clearTimeout(timer);if(d.toString()!=='ping')return reject(Error('bad websocket echo'));ws.close();resolve()});ws.on('error',reject)});
console.log(JSON.stringify({ok:true,htmlRewrite:true,cookieJar:true,postLogin:true,redirectRewrite:true,websocket:true}));
